In [1]:
import numpy as np

In [4]:
x=np.array([1,0,0])
y=np.array([0,1,0])
z=np.array([0,0,1])

In [60]:
#F = np.array([z,y,-x,-x,y,z]).T
F = np.array([x,y,x,z,-y,-z,-x,y,-x,-z,-y,z,-x,-y,-x,z,y,-z,x,-y,x,-z,y,z]).T

In [62]:
F

array([[ 1,  0,  1,  0,  0,  0, -1,  0, -1,  0,  0,  0, -1,  0, -1,  0,
         0,  0,  1,  0,  1,  0,  0,  0],
       [ 0,  1,  0,  0, -1,  0,  0,  1,  0,  0, -1,  0,  0, -1,  0,  0,
         1,  0,  0, -1,  0,  0,  1,  0],
       [ 0,  0,  0,  1,  0, -1,  0,  0,  0, -1,  0,  1,  0,  0,  0,  1,
         0, -1,  0,  0,  0, -1,  0,  1]])

In [63]:
sum(F.T)

array([0, 0, 0])

In [64]:
sum(abs(F.T))

array([8, 8, 8])

In [65]:
def beta_mat(F):
    Ft = F.T
    return np.array([np.cross(Ft[i],Ft[i+1]) for i in range(len(Ft)-1)]).T

In [66]:
beta = beta_mat(F)

In [67]:
sum(beta.T)

array([ 0, -1,  0])

In [68]:
def Pmat(vec1,vec2):
    return np.kron(vec1,vec2).reshape((3,3))+np.kron(vec2,vec1).reshape((3,3))

In [69]:
def P(F):
    Ft = F.T
    return np.array([Pmat(Ft[i],Ft[i+1]) for i in range(len(Ft)-1)])

In [70]:
sum(P(F))

array([[ 0,  0, -1],
       [ 0,  0,  0],
       [-1,  0,  0]])