In [2]:
import numpy as np
import nmresearch as nmr
import matplotlib.pyplot as plt
from pandas import DataFrame
from fermion import Math as fm

from timeit import default_timer as timer

ModuleNotFoundError: No module named 'pandas'

In [2]:
n=4

In [3]:
dq = f.Operator.double_quantum(n)
Z = f.Operator.global_Z(n)
xx = f.Operator.flipflop(n)

In [4]:
example = f.PauliString(["X", "Z"],[3,2],[True, False])

In [5]:
f.MajoranaString.from_pauli_string(example)

(5.656854249492381-0j) * A1(t)B1(t)A2(t)B2(t)A3(t)A2B2

In [3]:
5.656854249492381 * np.sqrt(2)

8.000000000000002

In [19]:
test = np.eye(2)
test[0,1]=1

In [20]:
test

array([[1., 1.],
       [0., 1.]])

In [21]:
test.transpose()

array([[1., 0.],
       [1., 1.]])

In [22]:
test

array([[1., 1.],
       [0., 1.]])